---
# tasks file for ansible-role-efs-lightsail

- name: Install nfs-utils (RedHat)
  package:
    name: nfs-utils
    state: present
  when: ansible_os_family == 'RedHat'

- name: Create directories for the mounts
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  with_items: "{{ aws_efs_paths }}"

- name: Mount paths vpc-local
  mount:
    name: "{{ item.path }}"
    src: "{{ availability_zone.content }}.{{ item.filesystem_id }}.efs.{{ item.region }}.amazonaws.com:/"
    fstype: nfs4
    opts: "{{ item.opts | default('nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport') }}"
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ aws_efs_paths }}"
  when: mount_type == "vpc-local"

- name: Mount paths vpc-peering
  mount:
    name: "{{ item.path }}"
    src: "{{ item.mount_target_ip }}.:/"
    fstype: nfs4
    opts: "{{ item.opts | default('nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2') }}"
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ aws_efs_paths }}"
  when: mount_type == "vpc-peering"
